apiVersion: v1
kind: ConfigMap
metadata:
  name: bookings-app-backend-envs
data:
  DB_PASSWORD: "docker"
  DB_URL: "jdbc:postgresql://postgres-service:5432/javadb?createDatabaseIfNotExist=true&useSSL=false"
  DB_NAME: "javadb"
  DB_USERNAME: "postgres"
  PORT: "8080"
  SECRET: "DaFcJfMhPmSpUrXuZw3z6B8EbGdJgNjQmTqVsXv2x4A7C9EcHeKgPkRnUrWtYw3y5A8DaFcJfMhQmSpUsXuZw4z6B8EbGdKgNjQn"
  TOKEN_EXPIRATION: "43200000"
  UPLOAD_DIR: "src/main/resources/uploads/images"
  FRONTEND_URLS: "http://localhost:3000;https://booking-app-matheusjustino.vercel.app"
