apiVersion: v1
kind: Service
metadata:
  name: bookings-app-backend-service
spec:
  selector:
    app: booking-app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
